# Homework 1: Insurance Portfolio Data Manipulation
Authors: Allyson Vasquez & Alex Miller

In [2]:
# imports
import pandas as pd
import numpy as np
import matplotlib

In [7]:
# 1 Create a pandas data frame, df1, using the data in the ‘example_portfolio.csv’ file. Make sure that 'PolicyNo' is the index of this dataframe.
df = pd.read_csv('example_portfolio.csv') 
df = df.set_index('PolicyNo')

In [8]:
# 2 Display the first 7 rows in the data frame
df.head(7)

,Policy_Company,Policy_Installment_Term,Policy_Billing_Code,Policy_Method_Of_Payment,Policy_Reinstatement_Fee_Indicator,Policy_Zip_Code_Garaging_Location,Vehicle_Territory,Vehicle_Make_Year,Vehicle_Make_Description,Vehicle_Performance,...,EEA_Prior_Bodily_Injury_Limit,EEA_PolicyYear,SYS_Renewed,SYS_New_Business,Annual_Premium,Claim_Count,Loss_Amount,Frequency,Severity,Loss_Ratio
PolicyNo,,,,,,,,,,,,,,,,,,,,,
164562033,Standard,6,Direct Billed to Insured,Pre-paid,N,42602,31,1990,DODG CARAVAN SE,Standard,...,20-50,2006,Y,N,111.30,0,0.0,0.0,0.0,0.0
165119133,Standard,6,Direct Billed to Insured,Pre-paid,N,42857,35,2001,BUIK REG LS-LSE,Standard,...,20-50,2006,Y,N,408.10,0,0.0,0.0,0.0,0.0
165166239,Standard,6,Direct Billed to Insured,Pre-paid,N,42980,30,1977,FORD TRUCK,Standard,...,100-400,2006,Y,N,125.08,0,0.0,0.0,0.0,0.0
165198832,Standard,6,Direct Billed to Insured,Installment,N,43050,35,2002,TYTA TUNDRA SR5,Standard,...,100-200,2006,Y,N,554.38,0,0.0,0.0,0.0,0.0
165319534,Standard,6,Direct Billed to Insured,Pre-paid,N,42496,35,1992,CHEV CAMARO RS,Sports,...,20-50,2006,Y,N,129.32,0,0.0,0.0,0.0,0.0
165355034,Standard,6,Direct Billed to Insured,Installment,N,42361,30,1992,FORD RANGER,Standard,...,20-50,2006,Y,N,279.84,0,0.0,0.0,0.0,0.0
165386232,Standard,6,Direct Billed to Insured,Pre-paid,N,42357,37,1955,CHEV BELAIR 2DR,Standard,...,40-100,2006,N,N,142.04,0,0.0,0.0,0.0,0.0

In [ ]:
# 3 Display the number of entries and data types of all fields

#TODO

In [ ]:
# 4 Create a new dataframe, df2, that contains only the following fields 
# 'Vehicle_Anti_Theft_Device', 'Driver_Minimum_Age', 'Vehicle_Age_In_Years', 'Annual_Premium', 'Loss_Amount'. 
# Note that 'PolicyNo' is the index of this dataframe as well. 
# To answer the following questions use df2.

#TODO

In [ ]:
# 5 Show the mean, std, min, and max for the numerical fields

In [ ]:
# 6 Show the unique values of 'Vehicle_Anti_Theft_Device'.

#TODO

In [ ]:
# 7 Calculate and print out the Portfolio Premium, Portfolio Loss, and Loss Ratio. 
# Portfolio Premium = sum of all the Annual Premiums of all the policies. 
# Portfolio Loss = sum of all the Loss Amounts of all the policies. 
# Loss Ratio = Portfolio Loss / Portfolio Premium.

# TODO

In [ ]:
# 8 Plot the histogram of 'Annual_Premium' field

# TODO

In [ ]:
# 9 Create a new data frame, df3, that groups the rows by Vehicle_Anti_Theft_Device and aggregates them by taking the mean for all the fields. 
# Note that the index of the new data frame should be Vehicle_Anti_Theft_Device. 
# To answer the following questions use df3.

#TODO

In [ ]:
# 10 Display the index of the new data frame
#TODO

In [ ]:
# 11 Create a new field 'Loss_Ratio' that gives the loss ratio per type of vehicle anti theft device. 
# Loss Ratio = Loss_Amount / Annual_Premium.

#TODO

In [ ]:
# 12 Sort the data frame by Loss Ratio in ascending order
#TODO

In [ ]:
# 13 Create a bar plot for 'Vehicle_Anti_Theft_Device' vs 'Loss_Ratio'.
#TODO

In [ ]:
# 14 In the notebook introduce a comment and answer the following question: 
# What conclusion can you draw from the bar plot above?

#TODO write commented answer here.

In [ ]:
# 15 Save the data in the df3 data frame into a file with the name 'summary.csv'
#TODO

In [ ]:
# 16 Create and display a numpy matrix using only the ‘Annual_Premium’ and ‘Loss_Amount’ fields.
#TODO

In [ ]:
# 17 Display the transpose of the new numpy matrix.
#TODO

In [ ]:
# 18 Create and display a copy of the third column of the transposed matrix. Make sure you use np.copy().
#TODO

In [ ]:
# 19 For data frame df1 create an html report for data exploration using pandas_profiling. 
# Save it into a file with the name 'example_portfolio_report.html'.
#TODO

In [ ]:
# 20 In the notebook introduce a comment to list at least three insights from the report that you are learning about the dataset.
#TODO write commented answer here.